# Generated by Django 5.1 on 2025-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0018_alter_feedback_nomeusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadoscampo",
            name="tipo_esporte",
            field=models.CharField(
                choices=[
                    ("futebol", "Futebol"),
                    ("basquete", "Basquete"),
                    ("volei", "Vôlei"),
                    ("tenis", "Tênis"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
